name: graphic_representation
description: easy graphic representation, using classes likes DiscreteGraphic for example. You can easily adapt your graphic with your android or ios device screen.
version: 1.0.7
Author: Patrick Auxerre
homepage: https://github.com/catpat44/graphic_representation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
